name: PyPI release

on: push

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry install
      - name: install go
        run: |
          sudo apt update
          sudo apt install golang-1.14-go -y
      - name: build helm bindings
        run: |
          bash "${VIRTUAL_ENV}/lib/python3.8/site-packages/kapitan/dependency_manager/helm/build.sh"
      - name: build commodore
        run: poetry build
      - name: publish to pypi
        run: |
          poetry config repositories.pypi_test https://test.pypi.org/legacy/
          poetry publish -u __token__ -p ${{ secrets.PYPI_TEST_TOKEN }} -r pypi_test
